[project @ 2007-07-20 16:08:21 by jwe]

diff --git a/mkoctfile.in b/mkoctfile.in
--- a/mkoctfile.in
+++ b/mkoctfile.in
@@ -253,7 +253,7 @@ EOF
       if [ $# -gt 0 ]; then
         incflags="$incflags -idirafter $1"
       else
-        echo "mkoctfile: include directory name misisng name missing" 1>&2
+        echo "mkoctfile: include directory name missing" 1>&2
       fi
     ;;
     -D*)
