[project @ 1998-04-24 04:24:34 by jwe]

diff --git a/kpathsea/mktexdir b/kpathsea/mktexdir
--- a/kpathsea/mktexdir
+++ b/kpathsea/mktexdir
@@ -1,23 +1,27 @@
 #!/bin/sh
-# mkinstalldirs --- make directory hierarchy (now MakeTeXmkdir).
+# mkinstalldirs --- make directory hierarchy (now mktexdir).
 # Author: Noah Friedman <friedman@prep.ai.mit.edu>, created: 1993-05-16.
 # Public domain.
 # 
 # Modified for sticky directory creation, --help, --version.
 # te@informatik.uni-hannover.de and kb@mail.tug.org.
 
-version='$Id: MakeTeXmkdir,v 1.1 1997-05-23 03:02:11 jwe Exp $'
+version='$Id: mktexdir,v 1.10 1998/03/16 23:15:36 olaf Exp $'
 usage="Usage: $0 DIRS...
   Create each DIR, including any missing leading directories."
 
-: ${TEXMFMAIN=`kpsewhich -expand-var='$TEXMFMAIN'`}
-if test -z "$TEXMFMAIN"; then
-  echo "$0: No \$TEXMFMAIN; set the environment variable or in texmf.cnf." >&2
+# Common code for all scripts.
+: ${MT_TEXMFMAIN=`kpsewhich --expand-path='$TEXMFMAIN'`}
+: ${MT_MKTEX_OPT=`kpsewhich --format='web2c files' mktex.opt`}
+test -n "$MT_MKTEX_OPT" || MT_MKTEX_OPT="$MT_TEXMFMAIN/web2c/mktex.opt"
+if test ! -f "$MT_MKTEX_OPT"; then
+  echo "$0: Cannot find mktex.opt; check your installation." >&2
   exit 1
 fi
-: ${TEXMFCNF_DIR=`kpsewhich -expand-var='$TEXMFCNF_DIR'`}
-test -n "$TEXMFCNF_DIR" || TEXMFCNF_DIR=$TEXMFMAIN/web2c
-. $TEXMFCNF_DIR/MakeTeXcommon
+
+. "$MT_MKTEX_OPT"
+
+test -n "$MT_MKTEXDIR_OPT" && . "$MT_MKTEXDIR_OPT"
 
 errstatus=0
 
@@ -30,12 +34,12 @@ do
    for d in ${1+"$@"} ; do
      pathcomp="$pathcomp$d"
      case "$pathcomp" in
-       -* ) pathcomp=./$pathcomp ;;
+       -* ) pathcomp="./$pathcomp" ;;
      esac
 
      if test ! -d "$pathcomp"; then
         mkdir "$pathcomp" || errstatus=$?
-        chmod $MT_DIR_PERMS $pathcomp
+        chmod `kpsestat ${MT_APPEND_MASK:-=} "$pathcomp"/..` "$pathcomp"
      fi
 
      pathcomp="$pathcomp/"
