[project @ 2002-10-10 05:20:20 by jwe]

diff --git a/scripts/mkdoc b/scripts/mkdoc
--- a/scripts/mkdoc
+++ b/scripts/mkdoc
@@ -1,11 +1,18 @@
 #! /bin/sh
 
+set -e
+
 if test $# != 1; then
   d=.
 else
   d=$1
 fi
 
-find $d -name '*.m' | \
-  sed "s,\(.*\)/\(.*\)\.m,./gethelp \2 < & | sed 's/^ *@/@/'," | \
-  /bin/sh
+if test -f gethelp; then
+  find $d -name '*.m' | \
+    sed "s,\(.*\)/\(.*\)\.m,./gethelp \2 < & | sed 's/^ *@/@/'," | \
+    /bin/sh
+else
+  echo "gethelp program seems to be missing!" 1>&2
+  exit 1
+fi
