make-cygwin.yaml: Update shell script to analyzes test results of GitHub runner
All other scripts were updated in cset 5252b2d3311e.  Accidentally missed this
one.

* make-cygwin.yaml: Print warning if at least one test has failed OR if there
  has been a regression.  When either warning has been printed, exit with
  status code 1 to flag this as unsuccesful.

diff --git a/.github/workflows/make-cygwin.yaml b/.github/workflows/make-cygwin.yaml
--- a/.github/workflows/make-cygwin.yaml
+++ b/.github/workflows/make-cygwin.yaml
@@ -287,8 +287,21 @@ jobs:
            done
 
       - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
-          echo Finished analyzing test suite results.
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"s
+        # "::warning::" or "::error::" will emit messages to the "Annotations"
+        # section of the workflow run.
+        run:  |
+          fail=0
+          if [ -z "$(grep -e 'FAIL\s*0' ./test-suite.log)" ]; then
+            echo "::error::At least one test failed"
+            fail=1
+          fi
+          if [ -n "$(grep -e 'REGRESSION' ./test-suite.log)" ]; then
+            echo "::error::At least one regression in test suite"
+            fail=1
+          fi
+          if [ $fail -eq 1 ]; then
+            exit 1
+          else
+            echo "No unknown failing tests."
+          fi
