Back out changeset: f5587d651bc7

diff --git a/.github/workflows/make.yaml b/.github/workflows/make.yaml
--- a/.github/workflows/make.yaml
+++ b/.github/workflows/make.yaml
@@ -294,7 +294,7 @@ jobs:
 
       - name: analyze test suite results
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
+        run:  |
           [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
           [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
           echo Finished analyzing test suite results.
@@ -519,11 +519,7 @@ jobs:
 
       - name: analyze test suite results
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        env:
-          MSYSTEM: ${{ matrix.msystem }}
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || \
-            ( [[ $MSYSTEM = "MINGW64" ]] && exit 1 || echo "::warning::At least one test failed" )
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || \
-            ( [[ $MSYSTEM = "MINGW64" ]] && exit 1 || echo "::warning::At least one regression in test suite" )
+        run:  |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
           echo Finished analyzing test suite results.
