Update shell scripts to analyze test results of GitHub runners.
* make-cross.yaml, make-macos.yaml, make-mingw.yaml, make-ubuntu.yaml:
Print warning if at least one test has failed OR if there has been a
regression.  When either warning has been printed, exit with status code 1 to
flag this as unsuccesful.

* make-alpine.yaml: Print warning if at least one test has failed.  When
warning printed, exit with status code 1 to flag this as unsuccesful.
Print a warning to Annotation section of log if a REGRESSION is detected, but
exit with status code 0 as 4 REGRESSIONs are expected.

diff --git a/.github/workflows/make-macos.yaml b/.github/workflows/make-macos.yaml
--- a/.github/workflows/make-macos.yaml
+++ b/.github/workflows/make-macos.yaml
@@ -246,8 +246,19 @@ jobs:
           done
 
       - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
-          echo No unknown failing tests.
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"s
+        run:  |
+          fail=0
+          if [ -z "$(grep -e 'FAIL\s*0' ./test-suite.log)" ]; then
+            echo "warning: At least one test failed"
+            fail=1
+          fi
+          if [ -n "$(grep -e 'REGRESSION' ./test-suite.log)" ]; then
+            echo "warning: At least one regression in test suite"
+            fail=1
+          fi
+          if [ $fail -eq 1 ]; then
+            exit 1
+          else
+            echo "No unknown failing tests."
+          fi
diff --git a/.github/workflows/make-ubuntu.yaml b/.github/workflows/make-ubuntu.yaml
--- a/.github/workflows/make-ubuntu.yaml
+++ b/.github/workflows/make-ubuntu.yaml
@@ -247,15 +247,15 @@ jobs:
         run:  |
           fail=0
           if [ -z "$(grep -e 'FAIL\s*0' ./test-suite.log)" ]; then
-            echo "warning: At least one test failed";
-            fail=1;
+            echo "warning: At least one test failed"
+            fail=1
           fi
           if [ -n "$(grep -e 'REGRESSION' ./test-suite.log)" ]; then
-            echo "warning: At least one regression in test suite";
-            fail=1;
+            echo "warning: At least one regression in test suite"
+            fail=1
           fi
           if [ $fail -eq 1 ]; then
-            exit 1;
+            exit 1
           else
-            echo "No unknown failing tests.";
+            echo "No unknown failing tests."
           fi
