GitHub-CI: Move step that might abort action until after more tests have run.
* .github/workflows/make.yaml: The "analyze test suite results" step might
abort a running action if at least one test failed unexpectedly in the test
suite. Move that test more to the end to allow running more steps before
potentially aborting.

diff --git a/.github/workflows/make.yaml b/.github/workflows/make.yaml
--- a/.github/workflows/make.yaml
+++ b/.github/workflows/make.yaml
@@ -148,13 +148,6 @@ jobs:
         timeout-minutes: 5
         run: cat ./.build/test/fntests.log
 
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run:  |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
-          echo No unknown failing tests.
-
       - name: test history file creation
         # see bug #62365
         # Pipe to an interactive session to trigger appending the command to
@@ -175,6 +168,13 @@ jobs:
           mkoctfile --link-stand-alone embedded.cc -o embedded
           LD_LIBRARY_PATH="/usr/local/lib/octave/$(octave --eval "disp(version())")" \
             ./embedded
+
+      - name: analyze test suite results
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        run:  |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
+          echo No unknown failing tests.
 
 
   alpine:
@@ -373,15 +373,6 @@ jobs:
         timeout-minutes: 5
         run: cat ./.build/test/fntests.log
 
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run:  |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] \
-            || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] \
-            || echo "::warning::At least one regression in test suite"
-          echo Finished analyzing test suite results.
-
       - name: test history file creation
         # see bug #62365
         # Pipe to an interactive session to trigger appending the command to
@@ -399,6 +390,15 @@ jobs:
           cd examples/code
           mkoctfile --link-stand-alone embedded.cc -o embedded
           LD_LIBRARY_PATH="/usr/local/lib/octave/$(octave --eval "disp(version())")" ./embedded
+
+      - name: analyze test suite results
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        run:  |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] \
+            || echo "::warning::At least one test failed"
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] \
+            || echo "::warning::At least one regression in test suite"
+          echo Finished analyzing test suite results.
 
 
   macos:
@@ -591,13 +591,6 @@ jobs:
         timeout-minutes: 5
         run: cat ./.build/test/fntests.log
 
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
-          echo No unknown failing tests.
-
       - name: test history file creation
         # see bug #62365
         # Pipe to an interactive session to trigger appending the command to
@@ -619,6 +612,13 @@ jobs:
           PATH="/Users/runner/usr/bin:$PATH" \
             mkoctfile --link-stand-alone embedded.cc -o embedded
           ./embedded
+
+      - name: analyze test suite results
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        run: |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
+          echo No unknown failing tests.
 
 
   mingw:
@@ -837,13 +837,6 @@ jobs:
         timeout-minutes: 5
         run: cat ./.build/test/fntests.log
 
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || (echo "::warning::At least one test failed" && exit 1)
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || (echo "::warning::At least one regression in test suite" && exit 1)
-          echo Finished analyzing test suite results.
-
       - name: test history file creation
         # see bug #62365
         # Pipe to an interactive session to trigger appending the command to
@@ -866,6 +859,13 @@ jobs:
           cd examples/code
           mkoctfile --link-stand-alone embedded.cc -o embedded
           ./embedded.exe
+
+      - name: analyze test suite results
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        run: |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || (echo "::warning::At least one test failed" && exit 1)
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || (echo "::warning::At least one regression in test suite" && exit 1)
+          echo Finished analyzing test suite results.
 
 
   cygwin:
@@ -1082,13 +1082,6 @@ jobs:
         timeout-minutes: 5
         run: cat ./.build/test/fntests.log
 
-      - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
-        run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
-          echo Finished analyzing test suite results.
-
       - name: test history file creation
         # see bug #62365
         # Pipe to an interactive session to trigger appending the command to
@@ -1109,3 +1102,10 @@ jobs:
           cd examples/code
           mkoctfile --link-stand-alone embedded.cc -o embedded
           ./embedded.exe
+
+      - name: analyze test suite results
+        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        run: |
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
+          echo Finished analyzing test suite results.
