GitHub-CI: Keep intentionally different coverage on stable and default branch.
* .github/workflows/make-mingw.yaml: Restore coverage from stable branch before
merge for Octave 11.

diff --git a/.github/workflows/make-mingw.yaml b/.github/workflows/make-mingw.yaml
--- a/.github/workflows/make-mingw.yaml
+++ b/.github/workflows/make-mingw.yaml
@@ -22,41 +22,23 @@ jobs:
 
       matrix:
         # For available GitHub-hosted runners, see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
-        msystem: [MINGW64, CLANG64, CLANGARM64]
+        os: [windows-latest]
+        msystem: [MINGW64, UCRT64]
         include:
           - msystem: MINGW64
-            os: windows-latest
             mingw-prefix: mingw64
             cc: gcc
             cxx: g++
             f77: gfortran
             extra-config-flags: ""
             ccache-max: 0.9G
-            allow-error: false
-          - msystem: CLANG64
-            os: windows-latest
-            mingw-prefix: clang64
-            cc: clang
-            cxx: clang++
-            f77: flang
-            # Clang seems to require a different set of dllexport attributes than GCC.
-            extra-config-flags:
-              --disable-lib-visibility-flags
-            ccache-max: 400M
-            # This configuration is not fully supported yet
-            allow-error: true
-          - msystem: CLANGARM64
-            os: windows-11-arm
-            mingw-prefix: clangarm64
-            cc: clang
-            cxx: clang++
-            f77: flang
-            # Clang seems to require a different set of dllexport attributes than GCC.
-            extra-config-flags:
-              --disable-lib-visibility-flags
-            ccache-max: 400M
-            # This configuration is not fully supported yet
-            allow-error: true
+          - msystem: UCRT64
+            mingw-prefix: ucrt64
+            cc: gcc
+            cxx: g++
+            f77: gfortran
+            extra-config-flags: ""
+            ccache-max: 0.9G
 
     env:
       CHERE_INVOKING: 1
@@ -78,9 +60,9 @@ jobs:
         with:
           update: true
 
-          # Use pre-installed version if possible to save disc space on
-          # partition with source.  We need that space for building.
-          release: ${{ matrix.msystem == 'CLANGARM64' }}
+          # Use pre-installed version to save disc space on partition with source.
+          # We need that space for building.
+          release: false
 
           msystem: ${{ matrix.msystem }}
 
@@ -261,7 +243,6 @@ jobs:
           make -C ./.build DESTDIR=/c/octave/pkg install
 
       - name: test stand-alone executable
-        continue-on-error: ${{ matrix.allow-error }}
         run: |
           unset CC
           unset CXX
@@ -272,7 +253,6 @@ jobs:
           ./embedded.exe
 
       - name: test Octave packages
-        continue-on-error: ${{ matrix.allow-error }}
         env:
           # colon separated list of packages
           # reasons for including these packages in the CI tests:
@@ -301,22 +281,6 @@ jobs:
       - name: analyze test suite results
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
         run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || (echo "::warning::At least one test failed" && exit 1)
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || (echo "::warning::At least one regression in test suite" && exit 1)
           echo Finished analyzing test suite results.
-
-      - name: compress build artifact
-        if: matrix.msystem == 'MINGW64'
-        continue-on-error: true
-        run: |
-          cd /c/octave/pkg
-          tar -cvzf octave.tar.gz *
-
-      - name: upload build artifact
-        if: matrix.msystem == 'MINGW64'
-        continue-on-error: true
-        uses: actions/upload-artifact@v6
-        with:
-          name: ${{ matrix.mingw-prefix }}-octave-${{ steps.ccache-prepare.outputs.timestamp }}
-          path: C:\octave\pkg\octave.tar.gz
-          retention-days: 7
