Update shell scripts to analyze test results of GitHub runners.
* make-cross.yaml, make-macos.yaml, make-mingw.yaml, make-ubuntu.yaml:
Print warning if at least one test has failed OR if there has been a
regression.  When either warning has been printed, exit with status code 1 to
flag this as unsuccesful.

* make-alpine.yaml: Print warning if at least one test has failed.  When
warning printed, exit with status code 1 to flag this as unsuccesful.
Print a warning to Annotation section of log if a REGRESSION is detected, but
exit with status code 0 as 4 REGRESSIONs are expected.
(grafted from 44906a6394a60f393df2433b998c8837534f783e)

diff --git a/.github/workflows/make-alpine.yaml b/.github/workflows/make-alpine.yaml
--- a/.github/workflows/make-alpine.yaml
+++ b/.github/workflows/make-alpine.yaml
@@ -271,10 +271,20 @@ jobs:
            done
 
       - name: analyze test suite results
-        # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
+        # Make sure the test summary lists 0 "FAIL"s.
+        # We have to tolerate 4 "REGRESSION"s (2026-08-18).
+        # "::warning::" syntax will put message in Annotation section of logs.
         run:  |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] \
-            || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] \
-            || echo "::warning::At least one regression in test suite"
-          echo Finished analyzing test suite results.
+          fail=0
+          if [ -z "$(grep -e 'FAIL\s*0' ./test-suite.log)" ]; then
+            echo "warning: At least one test failed"
+            fail=1
+          fi
+          if [ -n "$(grep -e 'REGRESSION' ./test-suite.log)" ]; then
+            echo "::warning:: At least one regression in test suite"
+          fi
+          if [ $fail -eq 1 ]; then
+            exit 1
+          else
+            echo "No unknown failing tests."
+          fi
