GitHub-CI (mingw): Mark run as failed on unexpected test suite error.
* .github/workflows/make.yaml (mingw): We have 0 FAILs or REGRESSIONs for the
MinGW environments we test on the stable branch. Mark the test run as failed
if that should regress.

diff --git a/.github/workflows/make.yaml b/.github/workflows/make.yaml
--- a/.github/workflows/make.yaml
+++ b/.github/workflows/make.yaml
@@ -796,8 +796,8 @@ jobs:
       - name: analyze test suite results
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
         run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || (echo "::warning::At least one test failed" && exit 1)
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || (echo "::warning::At least one regression in test suite" && exit 1)
           echo Finished analyzing test suite results.
 
       - name: test history file creation
